apiVersion: v1
kind: Service
metadata:
  name: enterprise-genai-service
spec:
  type: LoadBalancer
  selector:
    app: enterprise-genai-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
